management:
   security:
     enabled: false
server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-store-type: jks
    key-alias: linkdin
    key-password: password
---
spring:
 profiles: dev
server:
 port: 8000
---
spring:
 profile: prod
server:
 port: 9000